version: '3.6'
services:
  server:
    ports:
      - '8080:80'
  app:
    command: sh -c 'npm install && npm run start:watch'
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - node_modules:/app/node_modules
volumes:
  node_modules:
